version: "3.7"
services:
  cc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/user
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
